### ISSUE TITLE
[ci] Unpickling error for pretrained parameter loading

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-vision#36]
## 🐛 Bug

The `pretrained=True` option on models cannot be tested by CI, since passing it produces a `pickle` error that cannot be reproduced locally.

## To Reproduce

1. Running the `pkg-test` CI job on this [commit](https://github.com/frgfm/PyroNear/commit/079a2ee880cbdf37774d423a53bb4d2b471170e4)

which produces:
```
Traceback (most recent call last):
  File "/home/circleci/repo/test/test_models.py", line 22, in test_resnet
    model = models.resnet(depth=18, pretrained=True, bin_classif=True).eval()
  File "/home/circleci/repo/pyronear/models/resnet.py", line 49, in resnet
    progress=progress)
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/torch/hub.py", line 499, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/torch/serialization.py", line 603, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'Y'.
```

## Expected behavior

State dictionary loading should not produce errors.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/frgfm/PyroNear/master/pyronear/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/frgfm/PyroNear/master/pyronear/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version: 1.3.0
 - Torchvision Version: 0.4.1a0+d94043a
 - OS: Ubuntu 18.04
 - How you installed PyTorch: `conda`
 - Python version: 3.7
 - CUDA/cuDNN version: CUDA 10.1.168 / cuDNN 7.6.2
 - GPU models and configuration: GeForce GTX 1050 (driver: 430.50)

**Comment by frgfm** [comment]
This issue seems to have been fixed a while back, I'm not able to reproduce it anymore.
Closing for now, feel free to reopen if you encounter it!
